import type { Language } from '@/lib/i18n';

const copy = {
  tr: {
    liveWorkout: 'Canlı antrenman',
    liveWorkoutTitle: 'Formunu canlı kontrol et',
    liveWorkoutBody: 'Kamerayı aç, iskeletini gör ve her tekrarda anında geri bildirim al.',
    startLiveWorkout: 'Canlı antrenmanı başlat',
    liveSquat: 'Squat',
    livePushup: 'Şınav',
    liveLunge: 'Lunge',
    live: 'LIVE',
    stopLiveWorkout: 'Antrenmanı bitir',
    reps: 'tekrar',
    liveCameraPermissionTitle: 'Kameranı aç',
    liveCameraPermissionBody: 'Forge Fit, hareketini cihazında analiz etmek ve iskeletini göstermek için kameranı kullanır.',
    allowCamera: 'Kameraya izin ver',
    openSettings: 'Ayarları aç',
    cameraUnavailableTitle: 'Canlı analiz kullanılamıyor',
    cameraUnavailableBody: 'Bu özellik için Android development build ve kamera izni gerekir. Video kaydedilmez veya gönderilmez.',
    poseEngineError: 'İskelet motoru başlatılamadı. Lütfen uygulamayı yeniden açıp tekrar dene.',
    liveLookingForBody: 'Kameraya tam sığ ve görünür olduğundan emin ol.',
    liveStepBack: 'Biraz geriye çık. Tüm vücudun kadrajda görünsün.',
    liveMoveCloser: 'Biraz yaklaş. Hareketin kadraja sığdığından emin ol.',
    liveKneeAlignment: 'Dizini ayak bileğinle aynı hizada tut.',
    liveBackAngle: 'Sırtını daha dik ve kontrollü tut.',
    liveReachDepth: 'Biraz daha derine in.',
    liveHipPosition: 'Kalçanı omuzlarınla aynı çizgide tut.',
    liveElbowPosition: 'Dirseklerini kontrollü ve omuzlarının altında tut.',
    liveBalance: 'Dengeni koru ve iki tarafı eşit kullan.',
    liveTempo: 'Hareketi daha kontrollü yap.',
    liveGoodForm: 'Harika form — böyle devam et.',
    livePrivacyNote: 'Analiz cihazında gerçekleşir. Kamera görüntüsü kaydedilmez.',
  },
  en: {
    liveWorkout: 'Live workout',
    liveWorkoutTitle: 'Check your form live',
    liveWorkoutBody: 'Open the camera, see your skeleton and get instant feedback on every rep.',
    startLiveWorkout: 'Start the live workout',
    liveSquat: 'Squat',
    livePushup: 'Push-up',
    liveLunge: 'Lunge',
    live: 'LIVE',
    stopLiveWorkout: 'End workout',
    reps: 'reps',
    liveCameraPermissionTitle: 'Turn on your camera',
    liveCameraPermissionBody: 'Forge Fit uses your camera to analyze movement on your device and show your skeleton.',
    allowCamera: 'Allow camera',
    openSettings: 'Open settings',
    cameraUnavailableTitle: 'Live analysis is unavailable',
    cameraUnavailableBody: 'This feature needs an Android development build and camera access. Video is never recorded or uploaded.',
    poseEngineError: 'The skeleton engine could not start. Reopen the app and try again.',
    liveLookingForBody: 'Make sure your full body is visible in the camera.',
    liveStepBack: 'Step back a little so your whole body is in frame.',
    liveMoveCloser: 'Move a little closer while keeping your movement in frame.',
    liveKneeAlignment: 'Keep your knee aligned with your ankle.',
    liveBackAngle: 'Keep your back taller and controlled.',
    liveReachDepth: 'Go a little deeper.',
    liveHipPosition: 'Keep your hips in line with your shoulders.',
    liveElbowPosition: 'Keep your elbows controlled and under your shoulders.',
    liveBalance: 'Keep your balance and use both sides evenly.',
    liveTempo: 'Slow the movement down and stay controlled.',
    liveGoodForm: 'Great form — keep going.',
    livePrivacyNote: 'Analysis happens on your device. Camera video is never recorded.',
  },
  de: {
    liveWorkout: 'Live-Training',
    liveWorkoutTitle: 'Kontrolliere deine Form live',
    liveWorkoutBody: 'Öffne die Kamera, sieh dein Skelett und erhalte direktes Feedback bei jeder Wiederholung.',
    startLiveWorkout: 'Live-Training starten',
    liveSquat: 'Kniebeuge',
    livePushup: 'Liegestütz',
    liveLunge: 'Ausfallschritt',
    live: 'LIVE',
    stopLiveWorkout: 'Training beenden',
    reps: 'Wiederholungen',
    liveCameraPermissionTitle: 'Kamera aktivieren',
    liveCameraPermissionBody: 'Forge Fit nutzt deine Kamera, um deine Bewegung auf dem Gerät zu analysieren und dein Skelett zu zeigen.',
    allowCamera: 'Kamera erlauben',
    openSettings: 'Einstellungen öffnen',
    cameraUnavailableTitle: 'Live-Analyse nicht verfügbar',
    cameraUnavailableBody: 'Diese Funktion benötigt einen Android-Development-Build und Kamerazugriff. Videos werden weder gespeichert noch hochgeladen.',
    poseEngineError: 'Der Skelett-Tracker konnte nicht gestartet werden. Öffne die App erneut.',
    liveLookingForBody: 'Achte darauf, dass dein ganzer Körper sichtbar ist.',
    liveStepBack: 'Geh etwas zurück, damit dein ganzer Körper im Bild ist.',
    liveMoveCloser: 'Komm etwas näher und bleib im Bild.',
    liveKneeAlignment: 'Halte dein Knie über dem Fußgelenk.',
    liveBackAngle: 'Halte deinen Rücken aufrechter und kontrolliert.',
    liveReachDepth: 'Geh etwas tiefer.',
    liveHipPosition: 'Halte deine Hüfte auf einer Linie mit den Schultern.',
    liveElbowPosition: 'Halte die Ellbogen kontrolliert unter den Schultern.',
    liveBalance: 'Halte dein Gleichgewicht und arbeite beidseitig gleichmäßig.',
    liveTempo: 'Führe die Bewegung langsamer und kontrollierter aus.',
    liveGoodForm: 'Starke Form — weiter so.',
    livePrivacyNote: 'Die Analyse erfolgt auf deinem Gerät. Das Kamerabild wird nicht gespeichert.',
  },
  fr: {
    liveWorkout: 'Entraînement en direct',
    liveWorkoutTitle: 'Vérifie ta forme en direct',
    liveWorkoutBody: 'Ouvre la caméra, vois ton squelette et reçois un retour immédiat à chaque répétition.',
    startLiveWorkout: 'Démarrer l’entraînement en direct',
    liveSquat: 'Squat',
    livePushup: 'Pompes',
    liveLunge: 'Fente',
    live: 'LIVE',
    stopLiveWorkout: 'Terminer',
    reps: 'répétitions',
    liveCameraPermissionTitle: 'Active ta caméra',
    liveCameraPermissionBody: 'Forge Fit utilise ta caméra pour analyser tes mouvements sur ton appareil et afficher ton squelette.',
    allowCamera: 'Autoriser la caméra',
    openSettings: 'Ouvrir les réglages',
    cameraUnavailableTitle: 'Analyse en direct indisponible',
    cameraUnavailableBody: 'Cette fonction nécessite une version Android de développement et l’accès à la caméra. La vidéo n’est jamais enregistrée ni envoyée.',
    poseEngineError: 'Le suivi du squelette n’a pas pu démarrer. Rouvre l’app et réessaie.',
    liveLookingForBody: 'Vérifie que tout ton corps est visible dans la caméra.',
    liveStepBack: 'Recule un peu pour que tout ton corps soit dans le cadre.',
    liveMoveCloser: 'Rapproche-toi légèrement en restant dans le cadre.',
    liveKneeAlignment: 'Garde ton genou aligné avec ta cheville.',
    liveBackAngle: 'Garde le dos plus droit et contrôlé.',
    liveReachDepth: 'Descends un peu plus bas.',
    liveHipPosition: 'Garde tes hanches alignées avec tes épaules.',
    liveElbowPosition: 'Garde tes coudes contrôlés sous tes épaules.',
    liveBalance: 'Garde ton équilibre et travaille les deux côtés pareillement.',
    liveTempo: 'Ralentis le mouvement et reste contrôlé.',
    liveGoodForm: 'Très bonne forme — continue.',
    livePrivacyNote: 'L’analyse se fait sur ton appareil. La vidéo n’est jamais enregistrée.',
  },
  es: {
    liveWorkout: 'Entrenamiento en directo',
    liveWorkoutTitle: 'Comprueba tu técnica en directo',
    liveWorkoutBody: 'Abre la cámara, mira tu esqueleto y recibe feedback instantáneo en cada repetición.',
    startLiveWorkout: 'Iniciar entrenamiento en directo',
    liveSquat: 'Sentadilla',
    livePushup: 'Flexión',
    liveLunge: 'Zancada',
    live: 'LIVE',
    stopLiveWorkout: 'Terminar entrenamiento',
    reps: 'repeticiones',
    liveCameraPermissionTitle: 'Activa tu cámara',
    liveCameraPermissionBody: 'Forge Fit usa tu cámara para analizar el movimiento en tu dispositivo y mostrar tu esqueleto.',
    allowCamera: 'Permitir cámara',
    openSettings: 'Abrir ajustes',
    cameraUnavailableTitle: 'El análisis en directo no está disponible',
    cameraUnavailableBody: 'Esta función necesita una versión Android de desarrollo y acceso a la cámara. El vídeo nunca se guarda ni se sube.',
    poseEngineError: 'No se pudo iniciar el seguimiento del esqueleto. Abre la app de nuevo.',
    liveLookingForBody: 'Asegúrate de que todo tu cuerpo sea visible en la cámara.',
    liveStepBack: 'Aléjate un poco para que todo tu cuerpo entre en el encuadre.',
    liveMoveCloser: 'Acércate un poco sin salir del encuadre.',
    liveKneeAlignment: 'Mantén la rodilla alineada con el tobillo.',
    liveBackAngle: 'Mantén la espalda más erguida y controlada.',
    liveReachDepth: 'Baja un poco más.',
    liveHipPosition: 'Mantén las caderas alineadas con los hombros.',
    liveElbowPosition: 'Mantén los codos controlados bajo los hombros.',
    liveBalance: 'Mantén el equilibrio y trabaja ambos lados por igual.',
    liveTempo: 'Haz el movimiento más lento y controlado.',
    liveGoodForm: 'Muy buena técnica — sigue así.',
    livePrivacyNote: 'El análisis ocurre en tu dispositivo. El vídeo nunca se guarda.',
  },
} as const;

export type LiveWorkoutCopyKey = keyof typeof copy.tr;

export function liveTranslate(language: Language, key: LiveWorkoutCopyKey) {
  return copy[language][key] ?? copy.en[key];
}