import type { Language } from '@/lib/i18n';

const copy = {
  tr: {
    liveWorkout: 'Canlı antrenman',
    liveWorkoutTitle: 'Formunu canlı kontrol et',
    liveWorkoutBody: 'Kamerayı aç, iskeletini gör ve her tekrarda anında geri bildirim al.',
    startLiveWorkout: 'Canlı antrenmanı başlat',
    liveSquat: 'Squat',
    livePushup: 'Şınav',
    liveLunge: 'Lunge',
    livePushupView: 'Şınav: kameraya dön ve tüm vücudunu yatay olarak kadraja sığdır.',
    liveSquatView: 'Squat: kameraya önden dön, iki bacağını da görünür tut ve tam kadraja sığ.',
    liveLungeView: 'Lunge: kameraya yan dön ve öndeki bacağını tamamen göster.',
    live: 'LIVE',
    stopLiveWorkout: 'Antrenmanı bitir',
    reps: 'tekrar',
    hideRepsPanel: 'Tekrar panelini gizle',
    showRepsPanel: 'Tekrar panelini göster',
    liveCameraPlacement: 'En iyi deneyim için kameranı doğru konumlandırdığından emin ol.',
    liveFormGuideTitle: 'Doğru formu gör',
    liveFormGuideDismiss: 'Analize geç',
    liveFormGuideTip: 'Mavi iskelet çizgileri eklemlerinin hareketini takip eder. Gösterilen açıya yaklaşmaya çalış.',
    livePushupGuide: 'Kameraya dön, tüm vücudunu yatay olarak kadraja sığdır ve kollarını görünür tut.',
    liveSquatGuide: 'Kameraya önden dön, iki dizini de görünür tut ve tüm vücudunu kadrajda göster.',
    skeletonOnlyMode: 'Sadece iskeleti göster',
    cameraMode: 'Kamera görüntüsünü göster',
    liveLungeGuide: 'Kameraya yan dön, öndeki bacağını tamamen göster ve tüm vücudunu kadrajda tut.',
    liveCameraPermissionTitle: 'Kameranı aç',
    liveCameraPermissionBody: 'GainMode, hareketini cihazında analiz etmek ve iskeletini göstermek için kameranı kullanır.',
    allowCamera: 'Kameraya izin ver',
    openSettings: 'Ayarları aç',
    cameraUnavailableTitle: 'Canlı analiz kullanılamıyor',
    cameraUnavailableBody: 'Bu özellik için Android development build ve kamera izni gerekir. Video kaydedilmez veya gönderilmez.',
    poseEngineError: 'İskelet motoru başlatılamadı. Lütfen uygulamayı yeniden açıp tekrar dene.',
    liveLookingForBody: 'Kameraya tam sığ ve görünür olduğundan emin ol.',
    liveStepBack: 'Biraz geriye çık. Tüm vücudun kadrajda görünsün.',
    liveMoveCloser: 'Biraz yaklaş. Hareketin kadraja sığdığından emin ol.',
    liveKneeAlignment: 'Dizini ayak bileğinle aynı hizada tut.',
    liveBackAngle: 'Sırtını daha dik ve kontrollü tut.',
    liveReachDepth: 'Biraz daha derine in.',
    liveHipPosition: 'Kalçanı omuzlarınla aynı çizgide tut.',
    liveElbowPosition: 'Dirseklerini kontrollü ve omuzlarının altında tut.',
    liveBalance: 'Dengeni koru ve iki tarafı eşit kullan.',
    liveTempo: 'Hareketi daha kontrollü yap.',
    liveGoodForm: 'Harika form — böyle devam et.',
    livePrivacyNote: 'Analiz cihazında gerçekleşir. Kamera görüntüsü kaydedilmez.',
  },
  en: {
    liveWorkout: 'Live workout',
    liveWorkoutTitle: 'Check your form live',
    liveWorkoutBody: 'Open the camera, see your skeleton and get instant feedback on every rep.',
    startLiveWorkout: 'Start the live workout',
    liveSquat: 'Squat',
    livePushup: 'Push-up',
    liveLunge: 'Lunge',
    livePushupView: 'Push-up: face the camera and fit your full body horizontally in frame.',
    liveSquatView: 'Squat: face the camera, keep both legs visible, and fit your full body in frame.',
    liveLungeView: 'Lunge: turn sideways and keep your front leg fully visible.',
    live: 'LIVE',
    stopLiveWorkout: 'End workout',
    reps: 'reps',
    hideRepsPanel: 'Hide reps panel',
    showRepsPanel: 'Show reps panel',
    liveCameraPlacement: 'For the best experience, make sure your camera is positioned correctly.',
    liveFormGuideTitle: 'See the correct form',
    liveFormGuideDismiss: 'Start analysis',
    liveFormGuideTip: 'The blue skeleton tracks your joints. Try to match the demonstrated position and angle.',
    livePushupGuide: 'Face the camera, fit your full body horizontally in frame, and keep your arms visible.',
    liveSquatGuide: 'Face the camera, keep both knees visible, and show your whole body in frame.',
    skeletonOnlyMode: 'Show skeleton only',
    cameraMode: 'Show camera view',
    liveLungeGuide: 'Turn sideways, show your front leg fully, and keep your whole body in frame.',
    liveCameraPermissionTitle: 'Turn on your camera',
    liveCameraPermissionBody: 'GainMode uses your camera to analyze movement on your device and show your skeleton.',
    allowCamera: 'Allow camera',
    openSettings: 'Open settings',
    cameraUnavailableTitle: 'Live analysis is unavailable',
    cameraUnavailableBody: 'This feature needs an Android development build and camera access. Video is never recorded or uploaded.',
    poseEngineError: 'The skeleton engine could not start. Reopen the app and try again.',
    liveLookingForBody: 'Make sure your full body is visible in the camera.',
    liveStepBack: 'Step back a little so your whole body is in frame.',
    liveMoveCloser: 'Move a little closer while keeping your movement in frame.',
    liveKneeAlignment: 'Keep your knee aligned with your ankle.',
    liveBackAngle: 'Keep your back taller and controlled.',
    liveReachDepth: 'Go a little deeper.',
    liveHipPosition: 'Keep your hips in line with your shoulders.',
    liveElbowPosition: 'Keep your elbows controlled and under your shoulders.',
    liveBalance: 'Keep your balance and use both sides evenly.',
    liveTempo: 'Slow the movement down and stay controlled.',
    liveGoodForm: 'Great form — keep going.',
    livePrivacyNote: 'Analysis happens on your device. Camera video is never recorded.',
  },
  de: {
    liveWorkout: 'Live-Training',
    liveWorkoutTitle: 'Kontrolliere deine Form live',
    liveWorkoutBody: 'Öffne die Kamera, sieh dein Skelett und erhalte direktes Feedback bei jeder Wiederholung.',
    startLiveWorkout: 'Live-Training starten',
    liveSquat: 'Kniebeuge',
    livePushup: 'Liegestütz',
    liveLunge: 'Ausfallschritt',
    livePushupView: 'Liegestütz: Schau zur Kamera und bringe deinen ganzen Körper waagerecht ins Bild.',
    liveSquatView: 'Kniebeuge: Schau zur Kamera, halte beide Beine sichtbar und bleib vollständig im Bild.',
    liveLungeView: 'Ausfallschritt: Stell dich seitlich hin und zeige das vordere Bein vollständig.',
    live: 'LIVE',
    stopLiveWorkout: 'Training beenden',
    reps: 'Wiederholungen',
    hideRepsPanel: 'Wiederholungsanzeige ausblenden',
    showRepsPanel: 'Wiederholungsanzeige einblenden',
    liveCameraPlacement: 'Für die beste Erfahrung solltest du die Kamera richtig positionieren.',
    liveFormGuideTitle: 'Die richtige Form ansehen',
    liveFormGuideDismiss: 'Analyse starten',
    liveFormGuideTip: 'Das blaue Skelett verfolgt deine Gelenke. Versuche, Position und Winkel der Darstellung nachzuahmen.',
    livePushupGuide: 'Schau zur Kamera, bringe deinen ganzen Körper waagerecht ins Bild und halte die Arme sichtbar.',
    liveSquatGuide: 'Schau zur Kamera, halte beide Knie sichtbar und zeige deinen ganzen Körper im Bild.',
    skeletonOnlyMode: 'Nur Skelett anzeigen',
    cameraMode: 'Kamerabild anzeigen',
    liveLungeGuide: 'Stell dich seitlich hin, zeige das vordere Bein vollständig und bleib mit dem ganzen Körper im Bild.',
    liveCameraPermissionTitle: 'Kamera aktivieren',
    liveCameraPermissionBody: 'GainMode nutzt deine Kamera, um deine Bewegung auf dem Gerät zu analysieren und dein Skelett zu zeigen.',
    allowCamera: 'Kamera erlauben',
    openSettings: 'Einstellungen öffnen',
    cameraUnavailableTitle: 'Live-Analyse nicht verfügbar',
    cameraUnavailableBody: 'Diese Funktion benötigt einen Android-Development-Build und Kamerazugriff. Videos werden weder gespeichert noch hochgeladen.',
    poseEngineError: 'Der Skelett-Tracker konnte nicht gestartet werden. Öffne die App erneut.',
    liveLookingForBody: 'Achte darauf, dass dein ganzer Körper sichtbar ist.',
    liveStepBack: 'Geh etwas zurück, damit dein ganzer Körper im Bild ist.',
    liveMoveCloser: 'Komm etwas näher und bleib im Bild.',
    liveKneeAlignment: 'Halte dein Knie über dem Fußgelenk.',
    liveBackAngle: 'Halte deinen Rücken aufrechter und kontrolliert.',
    liveReachDepth: 'Geh etwas tiefer.',
    liveHipPosition: 'Halte deine Hüfte auf einer Linie mit den Schultern.',
    liveElbowPosition: 'Halte die Ellbogen kontrolliert unter den Schultern.',
    liveBalance: 'Halte dein Gleichgewicht und arbeite beidseitig gleichmäßig.',
    liveTempo: 'Führe die Bewegung langsamer und kontrollierter aus.',
    liveGoodForm: 'Starke Form — weiter so.',
    livePrivacyNote: 'Die Analyse erfolgt auf deinem Gerät. Das Kamerabild wird nicht gespeichert.',
  },
  fr: {
    liveWorkout: 'Entraînement en direct',
    liveWorkoutTitle: 'Vérifie ta forme en direct',
    liveWorkoutBody: 'Ouvre la caméra, vois ton squelette et reçois un retour immédiat à chaque répétition.',
    startLiveWorkout: 'Démarrer l’entraînement en direct',
    liveSquat: 'Squat',
    livePushup: 'Pompes',
    liveLunge: 'Fente',
    livePushupView: 'Pompes : regarde la caméra et fais entrer tout ton corps à l’horizontale dans le cadre.',
    liveSquatView: 'Squat : regarde la caméra, garde les deux jambes visibles et reste entièrement dans le cadre.',
    liveLungeView: 'Fente : place-toi de profil et garde la jambe avant entièrement visible.',
    live: 'LIVE',
    stopLiveWorkout: 'Terminer',
    reps: 'répétitions',
    hideRepsPanel: 'Masquer le panneau des répétitions',
    showRepsPanel: 'Afficher le panneau des répétitions',
    liveCameraPlacement: 'Pour une expérience optimale, veille à bien positionner ta caméra.',
    liveFormGuideTitle: 'Voir la bonne forme',
    liveFormGuideDismiss: 'Commencer l’analyse',
    liveFormGuideTip: 'Le squelette bleu suit tes articulations. Essaie de reproduire la position et l’angle montrés.',
    livePushupGuide: 'Regarde la caméra, fais entrer tout ton corps à l’horizontale dans le cadre et garde tes bras visibles.',
    liveSquatGuide: 'Regarde la caméra, garde les deux genoux visibles et montre tout ton corps dans le cadre.',
    skeletonOnlyMode: 'Afficher uniquement le squelette',
    cameraMode: 'Afficher la caméra',
    liveLungeGuide: 'Place-toi de profil, montre entièrement ta jambe avant et garde tout ton corps dans le cadre.',
    liveCameraPermissionTitle: 'Active ta caméra',
    liveCameraPermissionBody: 'GainMode utilise ta caméra pour analyser tes mouvements sur ton appareil et afficher ton squelette.',
    allowCamera: 'Autoriser la caméra',
    openSettings: 'Ouvrir les réglages',
    cameraUnavailableTitle: 'Analyse en direct indisponible',
    cameraUnavailableBody: 'Cette fonction nécessite une version Android de développement et l’accès à la caméra. La vidéo n’est jamais enregistrée ni envoyée.',
    poseEngineError: 'Le suivi du squelette n’a pas pu démarrer. Rouvre l’app et réessaie.',
    liveLookingForBody: 'Vérifie que tout ton corps est visible dans la caméra.',
    liveStepBack: 'Recule un peu pour que tout ton corps soit dans le cadre.',
    liveMoveCloser: 'Rapproche-toi légèrement en restant dans le cadre.',
    liveKneeAlignment: 'Garde ton genou aligné avec ta cheville.',
    liveBackAngle: 'Garde le dos plus droit et contrôlé.',
    liveReachDepth: 'Descends un peu plus bas.',
    liveHipPosition: 'Garde tes hanches alignées avec tes épaules.',
    liveElbowPosition: 'Garde tes coudes contrôlés sous tes épaules.',
    liveBalance: 'Garde ton équilibre et travaille les deux côtés pareillement.',
    liveTempo: 'Ralentis le mouvement et reste contrôlé.',
    liveGoodForm: 'Très bonne forme — continue.',
    livePrivacyNote: 'L’analyse se fait sur ton appareil. La vidéo n’est jamais enregistrée.',
  },
  es: {
    liveWorkout: 'Entrenamiento en directo',
    liveWorkoutTitle: 'Comprueba tu técnica en directo',
    liveWorkoutBody: 'Abre la cámara, mira tu esqueleto y recibe feedback instantáneo en cada repetición.',
    startLiveWorkout: 'Iniciar entrenamiento en directo',
    liveSquat: 'Sentadilla',
    livePushup: 'Flexión',
    liveLunge: 'Zancada',
    livePushupView: 'Flexión: mira a la cámara y encaja todo tu cuerpo en horizontal en el encuadre.',
    liveSquatView: 'Sentadilla: mira a la cámara, mantén visibles las dos piernas y encaja todo el cuerpo.',
    liveLungeView: 'Zancada: colócate de lado y mantén visible toda la pierna delantera.',
    live: 'LIVE',
    stopLiveWorkout: 'Terminar entrenamiento',
    reps: 'repeticiones',
    hideRepsPanel: 'Ocultar panel de repeticiones',
    showRepsPanel: 'Mostrar panel de repeticiones',
    liveCameraPlacement: 'Para disfrutar de la mejor experiencia, asegúrate de colocar bien la cámara.',
    liveFormGuideTitle: 'Mira la técnica correcta',
    liveFormGuideDismiss: 'Iniciar análisis',
    liveFormGuideTip: 'El esqueleto azul sigue tus articulaciones. Intenta imitar la posición y el ángulo mostrados.',
    livePushupGuide: 'Mira a la cámara, encaja todo tu cuerpo en horizontal y mantén los brazos visibles.',
    liveSquatGuide: 'Mira a la cámara, mantén visibles las dos rodillas y muestra todo el cuerpo en el encuadre.',
    skeletonOnlyMode: 'Mostrar solo el esqueleto',
    cameraMode: 'Mostrar la cámara',
    liveLungeGuide: 'Colócate de lado, muestra toda la pierna delantera y mantén todo el cuerpo en el encuadre.',
    liveCameraPermissionTitle: 'Activa tu cámara',
    liveCameraPermissionBody: 'GainMode usa tu cámara para analizar el movimiento en tu dispositivo y mostrar tu esqueleto.',
    allowCamera: 'Permitir cámara',
    openSettings: 'Abrir ajustes',
    cameraUnavailableTitle: 'El análisis en directo no está disponible',
    cameraUnavailableBody: 'Esta función necesita una versión Android de desarrollo y acceso a la cámara. El vídeo nunca se guarda ni se sube.',
    poseEngineError: 'No se pudo iniciar el seguimiento del esqueleto. Abre la app de nuevo.',
    liveLookingForBody: 'Asegúrate de que todo tu cuerpo sea visible en la cámara.',
    liveStepBack: 'Aléjate un poco para que todo tu cuerpo entre en el encuadre.',
    liveMoveCloser: 'Acércate un poco sin salir del encuadre.',
    liveKneeAlignment: 'Mantén la rodilla alineada con el tobillo.',
    liveBackAngle: 'Mantén la espalda más erguida y controlada.',
    liveReachDepth: 'Baja un poco más.',
    liveHipPosition: 'Mantén las caderas alineadas con los hombros.',
    liveElbowPosition: 'Mantén los codos controlados bajo los hombros.',
    liveBalance: 'Mantén el equilibrio y trabaja ambos lados por igual.',
    liveTempo: 'Haz el movimiento más lento y controlado.',
    liveGoodForm: 'Muy buena técnica — sigue así.',
    livePrivacyNote: 'El análisis ocurre en tu dispositivo. El vídeo nunca se guarda.',
  },
} as const;

export type LiveWorkoutCopyKey = keyof typeof copy.tr;

export function liveTranslate(language: Language, key: LiveWorkoutCopyKey) {
  return copy[language][key] ?? copy.en[key];
}